// Routes

export const ROUTES = {
AUTH: "/auth",
LOGIN: "login",
REGISTER: "register",
ADMIN: "/admin",
DASHBOARD: "dashboard",
ADMIN_PRODUCTS: "products",
ORDERS: "orders",
CREATE_ORDER: "createorder/:id?",
ADD_PRODUCT: "addproduct",
ADD_PRODUCT_EDIT: "addproduct/edit/:id",
SCAN_QR_CODE: "scanqrcode",
QR_CODE_DETAIL: "qrcodedetail/:id",
HOME: "/",
ACCOUNT: "account",
CHECKOUT: "checkout",
LISTING: "listing",
PRODUCT_DETAIL: "product-detail/:id",
PAYPAL_RETURN: "paypal-return",
ESEWA_RETURN: "esewa-return",
PAYMENT_SUCCESS: "payment-success",
PAYMENT_CANCEL: "payment-cancel",
SEARCH: "search",
LEGAL: "legal",
UNAUTH: "/unauth",
}